import '../styles/globals.scss'
import Navbar from '../components/Navbar'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import customTheme from '../styles/theme'
import { ChakraProvider } from '@chakra-ui/react'

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <ChakraProvider theme={customTheme}>
      <Head>
        <title>Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </ChakraProvider>
  )
}
export default MyApp
